export type Response = {
  order: (string & Number) | (number & Number);
  createdAt?: string;
  email_id?: string;
  name: string;
  description: string;
  logoUrl?: string;
  productUrl?: string;
  codeUrl?: string;
  projectUrls?: string;
  teamLeadName?: string;
  teamLeadEmail?: string;
  teamLeadSocialUrl?: string;
  teamMembersNames?: string;
  teamMembersEmails?: string;
  teamMembersSocialUrls?: string;
  teamLeadDiscordId?: string;
  teamMembersDiscordIds?: string;
  track: string;
  demoUrl?: string;
  category: string;
  superteamMember: string;
};

export const responses: Array<Response> = [
  {
    order: 1,
    createdAt: '3/17/2023 14:47:54',
    email_id: 'dhruvrajsinghsolanki161@gmail.com',
    name: 'Cubik',
    description:
      'Cubik is a decentralized funding tool that enables organizations to conduct fair quadratic funding rounds while also providing robust Sybil resistance. ',
    logoUrl: 'https://www.dropbox.com/s/lk5nyiey9d0ws9m/1-cubik.jpg?dl=1',
    productUrl: 'https://www.cubik.so/',
    codeUrl: 'https://github.com/cubik-so',
    projectUrls: '',
    teamLeadName: 'Dhruv',
    teamLeadEmail: 'dhruvrajsinghsolanki161@gmail.com',
    teamLeadSocialUrl:
      'https://twitter.com/dhruvraj641,https://twitter.com/IrffanAsiff',
    teamMembersNames: 'irfan',
    teamMembersEmails: 'hashtag.irfan@gmail.com',
    teamMembersSocialUrls: 'hashtag.irfan@gmail.com',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Payments',
    demoUrl: 'https://twitter.com/_cubik/status/1617816454967218178',
    category: 'Consumer dApps, DAOs and Communities',
    superteamMember: 'India',
  },
  {
    order: 2,
    createdAt: '3/17/2023 16:04:10',
    email_id: 'dhrumil@rootprotocol.org',
    name: 'Root Protocol',
    description:
      'Traders can trade SOL, BTC, ETH or literally any SPL token with 1000x leverage. This new derivative primitive works without liquidations and does not depend on any oracle.',
    logoUrl: 'https://www.dropbox.com/s/2bqp0y8jnzgq69x/2-root.png?dl=1',
    productUrl: 'https://leverage.rootprotocol.org/',
    codeUrl: 'https://github.com/root-hq/break-root',
    projectUrls: '',
    teamLeadName: 'Dhrumil Mehta',
    teamLeadEmail: 'dhrumil@rootprotocol.org',
    teamLeadSocialUrl: 'https://twitter.com/mmdhrumil',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DeFi',
    demoUrl: '',
    category: 'Consumer dApps, DeFi, Infrastructure, Mobile',
    superteamMember: 'India',
  },
  {
    order: 3,
    createdAt: '',
    email_id: 'heyaabis@gmail.com',
    name: 'SOL Trek',
    description: 'A visual and interactive Solana learning platform.',
    logoUrl:
      'https://api.typeform.com/responses/files/901f92e1bda32584e0bf84ac88f51b1aacd088417d858b902c38cea9da0d7ce3/Logo.png',
    productUrl: 'https://pitch.com/public/58fdcb12-5e7b-4c35-b8d4-10b689f1114e',
    codeUrl: 'https://github.com/GitBolt/SOLTrek',
    projectUrls: '',
    teamLeadName: 'Syed Aabis',
    teamLeadEmail: '',
    teamLeadSocialUrl: '',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Consumer, Tools & Infrastructure',
    demoUrl: '',
    category: 'Consumer, Tools & Infrastructure',
    superteamMember: 'India',
  },
  {
    order: 4,
    createdAt: '',
    email_id: 'mahajan13osheen@gmail.com',
    name: 'Saganize',
    description:
      'A Mobile Suite for dApps. A Tool Suite comprising of Products/SDKs/Libraries to onboard developers to build Solana Native Mobile dApps (Kotlin).',
    logoUrl:
      'https://api.typeform.com/responses/files/b5916c6249cf144023c4dc63d066f5a9505edeb570f8046e347bd7d706d90f91/F0B6121B_5B03_445B_9E88_2A68422579A2.jpeg',
    productUrl:
      'https://docs.google.com/file/d/1RrgQA6dXzm-NEBht4x2gC6aiBl3vfRQf/edit?usp=docslist_api&filetype=mspresentation',
    codeUrl: 'https://github.com/saganize',
    projectUrls: '',
    teamLeadName: 'Osh',
    teamLeadEmail: '',
    teamLeadSocialUrl: '',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile, Payments, Tools & Infrastructure, Consumer',
    demoUrl: '',
    category: 'Mobile, Payments, Tools & Infrastructure, Consumer',
    superteamMember: 'India',
  },
  {
    order: 5,
    createdAt: '',
    email_id: 'sahilpal67@gmail.com',
    name: 'Land deeds on blockchain as NFTs',
    description:
      'Solves the problem of land registration frauds using blockchain and patented approach',
    logoUrl:
      'https://api.typeform.com/responses/files/2bf4ea3ab18beaa79e15c1c026b43b5f944ac8a0367e25b002e2905604a3f75c/logo.jpg',
    productUrl:
      'https://drive.google.com/file/d/1uyVef-cO6I6Xn9y1OMiftR-ZHW1QKxeP/view?usp=share_link',
    codeUrl: 'https://github.com/sahil-pal/LandDeedsDapp',
    projectUrls: '',
    teamLeadName: 'sahil',
    teamLeadEmail: '',
    teamLeadSocialUrl: '',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DeFi, Consumer',
    demoUrl: '',
    category: 'DeFi, Consumer',
    superteamMember: 'Turkey',
  },
  {
    order: 6,
    createdAt: '',
    email_id: 'anishde2007@gmail.com',
    name: 'RayAuth',
    description:
      'Seamless onboarding infra for users and better transaction UX for users on Solana dApps',
    logoUrl:
      'https://api.typeform.com/responses/files/1a8767d5edfefd4cf5b19d0c758c4c31ac4276f71d5294f1b5cc25015ca74223/Logo___bg.png',
    productUrl: 'https://pitch.com/public/ee9a6602-b664-4358-9dfb-28085447c60f',
    codeUrl: 'https://github.com/AnishDe12020/rayauth',
    projectUrls: '',
    teamLeadName: 'Anish',
    teamLeadEmail: '',
    teamLeadSocialUrl: '',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Tools & Infrastructure, Consumer',
    demoUrl: '',
    category: 'Tools & Infrastructure, Consumer',
    superteamMember: 'India',
  },
  {
    order: 7,
    createdAt: '',
    email_id: 'atlantian001@dropchain.in',
    name: 'Atlantis DAO',
    description:
      'Mobile app built on Solana to earn from verifiable impact data points on chain, used by green and social impact projects.',
    logoUrl:
      'https://api.typeform.com/responses/files/ac4fb4b01e1f7e62e499a18fb6f96155f1150ad65a9e8c373e63f741772663b3/Atlantis_DAO_Logo.png',
    productUrl:
      'https://drive.google.com/drive/folders/1a2_qLJLnEMAHDj6qil1yK7mRk8qX5Prn?usp=share_link',
    codeUrl: 'https://github.com/AtlantisDAO1/atlantis-blockchain',
    projectUrls: '',
    teamLeadName: 'Irthu',
    teamLeadEmail: '',
    teamLeadSocialUrl: '',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DAOs and Network States, Mobile, Consumer',
    demoUrl: '',
    category: 'DAOs and Network States, Mobile, Consumer',
    superteamMember: 'India',
  },
  {
    order: 8,
    createdAt: '',
    email_id: 'adil@vayoo.markets',
    name: 'Vayoo Markets',
    description:
      'Building a scalable solution on providing onchain-liquidity for traditional markets. \n\nEnabling you to trade equity / rates / commodity..etc\n\neg: SPX, NIFTY',
    logoUrl:
      'https://api.typeform.com/responses/files/6002ed5799b3947812d4495d2acf81ecefb6ae7137c0dbd0942531570612fdc2/vayoo_logo.jpg',
    productUrl:
      'https://drive.google.com/file/d/1msZp0xGupDDT1W9is_5NhFwraoJaHS1a/view?usp=sharing',
    codeUrl: 'https://github.com/orgs/Vayoo-Labs/repositories',
    projectUrls: '',
    teamLeadName: 'Muhammed',
    teamLeadEmail: '',
    teamLeadSocialUrl: '',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DeFi, Consumer',
    demoUrl: '',
    category: 'DeFi, Consumer',
    superteamMember: 'India',
  },
  {
    order: 9,
    createdAt: '',
    email_id: 'raj@truts.xyz',
    name: 'Truts',
    description:
      'Discovery platform for web3 projects with metrics like missions, reviews, social details and others',
    logoUrl:
      'https://api.typeform.com/responses/files/a7f2c25efeede377d8859db250aebd3825bb462fd9c97ecff6affa000791d6b7/Truts_Logo_1.png',
    productUrl: 'https://pitch.com/public/f2c1183a-67ea-4635-b9f2-201077122df4',
    codeUrl: 'https://we.haveSubmitted.onmail',
    projectUrls: '',
    teamLeadName: 'Raj',
    teamLeadEmail: '',
    teamLeadSocialUrl: '',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DAOs and Network States, Consumer, Tools & Infrastructure, Mobile',
    demoUrl: '',
    category:
      'DAOs and Network States, Consumer, Tools & Infrastructure, Mobile',
    superteamMember: 'India',
  },
  {
    order: 10,
    createdAt: '',
    email_id: 'bhagyamudgal@gmail.com',
    name: 'NotiSol',
    description:
      'The multi-channel notification service for all your Solana wallet activity.',
    logoUrl:
      'https://api.typeform.com/responses/files/3bfeb871ab5237b47db9815be3a0b175af454a136b8772e10c6f1d12298de81c/logo.png',
    productUrl:
      'https://docs.google.com/presentation/d/1DhR929RLINQ3v7iJ1HZ_oLVRqfq9G_05/edit?usp=sharing&ouid=106554495818436960579&rtpof=true&sd=true',
    codeUrl: 'https://github.com/bhagyamudgal/notisol',
    projectUrls: '',
    teamLeadName: 'Bhagya',
    teamLeadEmail: '',
    teamLeadSocialUrl: '',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Consumer, Tools & Infrastructure',
    demoUrl: '',
    category: 'Consumer, Tools & Infrastructure',
    superteamMember: 'Vietnam',
  },
  {
    order: 11,
    createdAt: '',
    email_id: 'akshay93aditya@gmail.com',
    name: 'proto',
    description:
      'proto is an api for spatial data and proof of location \n on solana.',
    logoUrl:
      'https://api.typeform.com/responses/files/1c80fb2c8fc5d7c9aa02f683cf87e22c51d0c98f12ed49a5d0c4a58343b0984e/Group_39001.png',
    productUrl: 'https://pitch.com/public/e9e3e5d6-8254-493c-8432-c1e78ef8c467',
    codeUrl: 'https://github.com/orgs/de-planDAO/repositories',
    projectUrls: '',
    teamLeadName: 'Akshay',
    teamLeadEmail: '',
    teamLeadSocialUrl: '',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Tools & Infrastructure, Mobile',
    demoUrl: '',
    category: 'Tools & Infrastructure, Mobile',
    superteamMember: 'Mexico',
  },
  {
    order: 12,
    createdAt: '',
    email_id: 'kb24x7@gmail.com',
    name: 'QuickBasket',
    description:
      'An open-sourced self checkout app that allows customers to tap any product in an IRL store and pay for it through their phones.',
    logoUrl:
      'https://api.typeform.com/responses/files/6915df05ef2c2838b8d90052e398f98ee7e5a6d6df49a1c14a8feec43f5a403f/Qb_1.png',
    productUrl: 'https://pitch.com/v/quickbasket-uuwukb',
    codeUrl: 'https://github.com/KunalBagaria/QuickBasket',
    projectUrls: '',
    teamLeadName: 'Kunal',
    teamLeadEmail: '',
    teamLeadSocialUrl: '',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile, Payments, Consumer',
    demoUrl: '',
    category: 'Mobile, Payments, Consumer',
    superteamMember: 'Mexico',
  },
  {
    order: 13,
    createdAt: '',
    email_id: 'shukarsh@gmail.com',
    name: 'Cordelia',
    description: 'Treasury Management Solution for DAOs and Web3 communities',
    logoUrl:
      'https://api.typeform.com/responses/files/789032a8ad5e1f2fc764fc4eaa79ec8c5af99611365a767eb6fad4e880ec0bb7/icon.png',
    productUrl:
      'https://docs.google.com/presentation/d/1TgxJqSEx4xa9sasdJsJawFZisGM7OB5b_smFjr-pLXo/edit?usp=sharing',
    codeUrl: 'https://github.com/Cordelia-Program/Cordelia-Anchor',
    projectUrls: '',
    teamLeadName: 'Utkarsh',
    teamLeadEmail: '',
    teamLeadSocialUrl: '',
    teamMembersNames: 'Rahul,Ramesh,Suresh,Mahesh',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DAOs and Network States',
    demoUrl: '',
    category: 'DAOs and Network States',
    superteamMember: 'Germany',
  },
];
