export type Response = {
  order: (string & Number) | (number & Number);
  createdAt?: string;
  email_id?: string;
  name: string;
  description: string;
  logoUrl?: string;
  productUrl?: string;
  codeUrl?: string;
  projectUrls?: string;
  teamLeadName?: string;
  teamLeadEmail?: string;
  teamLeadSocialUrl?: string;
  teamMembersNames?: string;
  teamMembersEmails?: string;
  teamMembersSocialUrls?: string;
  teamLeadDiscordId?: string;
  teamMembersDiscordIds?: string;
  track: string;
  demoUrl?: string;
  category: string;
  superteamMember: string;
};

export const responses: Array<Response> = [
  {
    order: 1,
    createdAt: '3/17/2023 14:47:54',
    email_id: 'dhruvrajsinghsolanki161@gmail.com',
    name: 'Cubik',
    description:
      'Cubik is a decentralized funding tool that enables organizations to conduct fair quadratic funding rounds while also providing robust Sybil resistance. ',
    logoUrl: 'https://www.dropbox.com/s/lk5nyiey9d0ws9m/1-cubik.jpg?dl=1',
    productUrl: 'https://www.cubik.so/',
    codeUrl: 'https://github.com/cubik-so',
    projectUrls: '',
    teamLeadName: 'Dhruv',
    teamLeadEmail: 'dhruvrajsinghsolanki161@gmail.com',
    teamLeadSocialUrl:
      'https://twitter.com/dhruvraj641,https://twitter.com/IrffanAsiff',
    teamMembersNames: 'irfan',
    teamMembersEmails: 'hashtag.irfan@gmail.com',
    teamMembersSocialUrls: 'hashtag.irfan@gmail.com',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Payments',
    demoUrl: 'https://twitter.com/_cubik/status/1617816454967218178',
    category: 'Consumer dApps, DAOs and Communities',
    superteamMember: 'India',
  },
  {
    order: 2,
    createdAt: '3/17/2023 16:04:10',
    email_id: 'dhrumil@rootprotocol.org',
    name: 'Root Protocol',
    description:
      'Traders can trade SOL, BTC, ETH or literally any SPL token with 1000x leverage. This new derivative primitive works without liquidations and does not depend on any oracle.',
    logoUrl: 'https://www.dropbox.com/s/2bqp0y8jnzgq69x/2-root.png?dl=1',
    productUrl: 'https://leverage.rootprotocol.org/',
    codeUrl: 'https://github.com/root-hq/break-root',
    projectUrls: '',
    teamLeadName: 'Dhrumil Mehta',
    teamLeadEmail: 'dhrumil@rootprotocol.org',
    teamLeadSocialUrl: 'https://twitter.com/mmdhrumil',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DeFi',
    demoUrl: '',
    category: 'Consumer dApps, DeFi, Infrastructure, Mobile',
    superteamMember: 'India',
  },
  {
    order: 3,
    createdAt: '3/18/2023 22:51:39',
    email_id: 'kharangateanoushk04@gmail.com',
    name: 'Tinydancer ',
    description: 'A light client for Solana',
    logoUrl:
      'https://pbs.twimg.com/profile_images/1628722617334267905/s7UFpQtX_400x400.jpg',
    productUrl: 'https://github.com/tinydancer-io/half-baked-client',
    codeUrl: 'https://github.com/tinydancer-io',
    projectUrls: '',
    teamLeadName: 'Anoushk Kharangate',
    teamLeadEmail: 'kharangateanoushk04@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/anoushk77',
    teamMembersNames: 'Harsh Patel',
    teamMembersEmails: 'hp80738@gmail.com',
    teamMembersSocialUrls: 'https://twitter.com/harsh4786',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile, Payments, Tools & Infrastructure',
    demoUrl: 'https://www.loom.com/share/ef3ad02be8bf481eac4b728ef8ce3d89',
    category: '',
    superteamMember: 'India',
  },
  {
    order: 4,
    createdAt: '3/19/2023 4:17:41',
    email_id: 'akshay93aditya@gmail.com',
    name: 'proto',
    description:
      'proto is an api for spatial data and proof of location on solana.',
    logoUrl:
      'https://api.typeform.com/responses/files/1c80fb2c8fc5d7c9aa02f683cf87e22c51d0c98f12ed49a5d0c4a58343b0984e/Group_39001.png',
    productUrl: 'https://www.proto-geo.xyz',
    codeUrl: 'https://github.com/orgs/de-planDAO/repositories',
    projectUrls: '',
    teamLeadName: 'Akshay',
    teamLeadEmail: 'akshay93aditya@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/thede_plandude',
    teamMembersNames: 'Shreyash,King,Abhishek',
    teamMembersEmails: 'shreyash.addepalli@gmail.com,dmadhur6@gmail.com,',
    teamMembersSocialUrls:
      'https://twitter.com/Shreyash_1599,https://twitter.com/Chester_King__,https://twitter.com/abhwshek',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile, Tools & Infrastructure',
    demoUrl: 'https://www.loom.com/share/1c6008ec74e44d19b9eb2f72ecac3dee',
    category: '',
    superteamMember: 'India',
  },
  {
    order: 5,
    createdAt: '3/19/2023 23:14:45',
    email_id: 'kb24x7@gmail.com',
    name: 'QuickBasket',
    description:
      'An open-sourced self checkout app that allows customers to tap any product in an IRL store and pay for it through their phones.',
    logoUrl:
      'https://pbs.twimg.com/profile_images/1632134803142377473/ry41emQV_400x400.jpg',
    productUrl: 'https://github.com/KunalBagaria/QuickBasket',
    codeUrl: 'https://github.com/KunalBagaria/QuickBasket',
    projectUrls: '',
    teamLeadName: 'Kunal Bagaria',
    teamLeadEmail: 'kb24x7@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/kb24x7',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile, Payments, Consumer',
    demoUrl: 'https://pitch.com/v/quickbasket-uuwukb',
    category: '',
    superteamMember: 'India',
  },
  {
    order: 6,
    createdAt: '3/19/2023 23:18:18',
    email_id: 'arihant.bansal@gmail.com',
    name: 'Blizz',
    description:
      'Blizzard is a fully-permissionless DEX for trading perpetual contracts. ',
    logoUrl: '',
    productUrl: 'https://tradeblizzard.vercel.app/',
    codeUrl: 'https://github.com/sandblizzard/perpetuals',
    projectUrls: '',
    teamLeadName: 'Arihant Bansal',
    teamLeadEmail: 'arihant.bansal@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/_arihantbansal',
    teamMembersNames: 'Kiran, Kristoffer',
    teamMembersEmails: '',
    teamMembersSocialUrls:
      'https://twitter.com/Kiranjaimon, https://twitter.com/0xksure',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DeFi',
    demoUrl:
      'https://docs.google.com/presentation/d/1LmRj_lx5xE3m6PJIiMSAvCMqVQz3eZWRiey1lg7zrG8/edit#slide=id.g11f1c526541_0_0',
    category: '',
    superteamMember: 'India',
  },
  {
    order: 7,
    createdAt: '3/19/2023 23:24:52',
    email_id: 'enigmaticabhisek@gmail.com',
    name: 'defiOS',
    description: 'Scaling Layer for Open Source Collaboration',
    logoUrl:
      'https://www.defi-os.com/_next/image?url=/_next/static/media/logo-full.f32bfc25.png&w=384&q=75',
    productUrl:
      'https://twitter.com/defiOSofficial/status/1636458712083705856?s=20',
    codeUrl: 'https://github.com/defi-os',
    projectUrls: '',
    teamLeadName: 'Abhisek Basu',
    teamLeadEmail: 'enigmaticabhisek@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/_AbhisekBasu',
    teamMembersNames: 'Priyesh',
    teamMembersEmails: 'priyesh@defi-os.com',
    teamMembersSocialUrls: 'https://twitter.com/chained_alchemy',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track:
      'DeFi, Payments, Consumer, Tools & Infrastructure, DAOs and Network States',
    demoUrl: '',
    category: '',
    superteamMember: 'India',
  },
  {
    order: 8,
    createdAt: '3/20/2023 0:31:25',
    email_id: 'magio@magiobus.com',
    name: 'Soles & Dragons',
    description:
      'Create your own fictional role characters using AI and collect them as unique NFTs sent directly to your Solana wallet.',
    logoUrl: '',
    productUrl: 'https://solesanddragons.vercel.app',
    codeUrl: 'https://github.com/magiobus/solesanddragons',
    projectUrls: '',
    teamLeadName: 'Magio Bustillos',
    teamLeadEmail: 'magio@magiobus.com',
    teamLeadSocialUrl: 'https://twitter.com/magiobus',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Consumer, Gaming',
    demoUrl: 'https://solesanddragons.vercel.app',
    category: '',
    superteamMember: 'Mexico',
  },
  {
    order: 9,
    createdAt: '3/20/2023 2:04:47',
    email_id: 'dlgrech91@gmail.com',
    name: 'Solguard',
    description:
      'Helping you break your addiction to your phone while making charitable donations ',
    logoUrl:
      'https://raw.githubusercontent.com/dlgrech/solguard/main/android/app/ic_launcher-playstore.png',
    productUrl: 'https://twitter.com/solguard_app',
    codeUrl: 'https://github.com/dlgrech/solguard',
    projectUrls: '',
    teamLeadName: 'dlg',
    teamLeadEmail: 'dlgrech91@gmail.com',
    teamLeadSocialUrl: 'https://discord.com/users/900323346036695050',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile',
    demoUrl:
      'https://www.canva.com/design/DAFdA6l9j-E/r69kOCjmhCAuubjPqB-ukg/view',
    category: '',
    superteamMember: 'India',
  },
  {
    order: 10,
    createdAt: '3/20/2023 4:18:31',
    email_id: 'cm@monstre.net',
    name: 'MonstrèPay',
    description:
      'Integrating with Tiplink and Stripe that provides step-by-step instructions via Gmail after each successful transaction, making it easy for merchants and crypto-curious users to start using Web3.',
    logoUrl: 'https://www.dropbox.com/s/4y8575ihcjk5phh/10-monstre.png?dl=1',
    productUrl: 'https://monstre-tiplink.herokuapp.com/',
    codeUrl: 'https://github.com/cutemonstersnft',
    projectUrls: '',
    teamLeadName: 'CM',
    teamLeadEmail: 'cm@monstre.net',
    teamLeadSocialUrl:
      'https://twitter.com/cm_monstre?s=21&t=YReMmEjDdePK90Zpawq7Tw',
    teamMembersNames: 'Fatalty',
    teamMembersEmails: 'fatalty@monstre.net',
    teamMembersSocialUrls: 'https://twitter.com/amirincrypto',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Payments, Consumer',
    demoUrl: 'https://youtu.be/QH1GjCn7-2A',
    category: '',
    superteamMember: 'India',
  },
  {
    order: 11,
    createdAt: '3/20/2023 15:25:40',
    email_id: 'deancpappas@gmail.com',
    name: "Dean's List",
    description: 'A network state for power users and early adopters',
    logoUrl: 'https://i.imgur.com/tYLrPuL.png',
    productUrl: 'https://www.deanslist.services/networkstate',
    codeUrl: 'https://github.com/orgs/Deans-List/repositories',
    projectUrls: '',
    teamLeadName: 'Dean Pappas',
    teamLeadEmail: '',
    teamLeadSocialUrl: 'https://twitter.com/_dean_machine',
    teamMembersNames: '69 people across the world!',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DAOs and Network States',
    demoUrl:
      'https://docs.google.com/presentation/d/1jEjrKNvu3WrDTwj5XM1SKrUmyqly0V7De_hCkL9l1Mc/edit#slide=id.g1f34a68df28_4_3',
    category: '',
    superteamMember: 'India',
  },
  {
    order: 12,
    createdAt: '3/20/2023 21:39:36',
    email_id: 'hector@vulcanics.mx',
    name: 'Little Bonkers',
    description:
      'Proof of Play Game on Solana. Play while validating blockchain transactions.',
    logoUrl:
      'https://littlebonkers.xyz/wp-content/uploads/2023/01/cropped-Little_Bonkers_Logo.png',
    productUrl: 'https://littlebonkers.xyz',
    codeUrl: 'https://github.com/LittleBonkers/Little-Bonkers/',
    projectUrls: '',
    teamLeadName: 'Hector Lara',
    teamLeadEmail: 'Hector@vulcanics.mx',
    teamLeadSocialUrl: '',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile, Consumer, Gaming',
    demoUrl: 'https://play.littlebonkers.xyz',
    category: '',
    superteamMember: 'Mexico',
  },
  {
    order: 13,
    createdAt: '3/20/2023 21:54:14',
    email_id: 'hello@candypay.fun',
    name: 'CandyPay',
    description:
      'CandyPay is a no-code platform powering seamless, mobile native payment experiences on Solana! ',
    logoUrl:
      'https://res.cloudinary.com/dtzqgftjk/image/upload/v1674324595/2_cdaoyi_2_caoflv.png',
    productUrl: 'https://candypay.fun',
    codeUrl: 'https://github.com/candypay/elements',
    projectUrls: '',
    teamLeadName: 'Umang',
    teamLeadEmail: 'umang@candypay.fun',
    teamLeadSocialUrl: 'https://twitter.com/umang_veerma',
    teamMembersNames: 'Mukesh, Anurag',
    teamMembersEmails: 'mukesh@candypay.fun',
    teamMembersSocialUrls:
      'https://twitter.com/0xMukesh, https://twitter.com/imanuraglol',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile, Payments, Tools & Infrastructure',
    demoUrl:
      'https://pitch.com/public/7439a220-8d0d-4d53-bcb4-c80b4435cda9/c5507d23-5c62-4ed3-a8bb-8ff5f02901b1',
    category: '',
    superteamMember: 'India',
  },
  {
    order: 14,
    createdAt: '3/21/2023 8:52:21',
    email_id: 'palacioscarla35@gmail.com',
    name: 'Ticket Munster',
    description: 'Ticket Validation Through NFT',
    logoUrl:
      'https://drive.google.com/file/d/1PrMnMJ5gRN2ZGrOjOw3GyQd2B5dDCBad/view?usp=sharing',
    productUrl: '',
    codeUrl: 'https://github.com/OzPineapple/hackaton',
    projectUrls: '',
    teamLeadName: 'Palacios Alvarado Carla ',
    teamLeadEmail: 'palacioscarla35@gmail.com',
    teamLeadSocialUrl: 'https://www.facebook.com/carla.palacios.520/',
    teamMembersNames:
      'AMARO ROMERO ROBERTO FERNANDO\nGARCIA FRANCO ANGEL EDUARDO \nMONTIEL GÓMEZ ERIK ALAIN \nCORTES PIÑA OZIEL ',
    teamMembersEmails:
      'romaro1101@gmail.com \nMaya-chan123@outlook.com\nalainmontiel479@gmail.com\nozielcortespinna@gmail.com\n',
    teamMembersSocialUrls:
      'https://www.facebook.com/ImAHelperCat\nhttps://www.facebook.com/profile.php?id=100007421137139\nhttps://www.facebook.com/erik.montiel.7549\nhttps://www.facebook.com/oz.pineapple.9',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DeFi, Payments, Consumer',
    demoUrl: 'https://youtu.be/j07UKDVPc8M',
    category: '',
    superteamMember: 'Mexico',
  },
  {
    order: 15,
    createdAt: '3/21/2023 16:05:40',
    email_id: 'minhnlh19@gmail.com',
    name: 'Mochi DAO',
    description:
      'Mochi DAO provides solutions for DAO communities development on Discord. \nMochi Bot promises to automate the voting and decision making process. All users need to do is set-and-go.',
    logoUrl:
      'https://drive.google.com/file/d/1fEVhieXA045HocZWWIfVgqwi1uKVDP4C/view?usp=share_link',
    productUrl: 'https://mochi.gg/',
    codeUrl: 'https://github.com/consolelabs/mochi-discord',
    projectUrls: '',
    teamLeadName: 'Nguyen Hoang Huy',
    teamLeadEmail: 'hoanghuy2908@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/_hnh2908',
    teamMembersNames:
      'Long "Leo" Pham,Hien-Minh Nguyen-Le,Phuc Le Dien,Cat Nguyen Hoang,Hoang Ho Minh',
    teamMembersEmails:
      'leo@console.so,minhnlh19@gmail.com,phucledien@gmail.com,hoangcat622001@gmail.com,hoang.ho.it99@gmail.com',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DAOs and Network States',
    demoUrl:
      'https://drive.google.com/file/d/1AdNU1eU8mXt8iprykXiRM5ln2WSvNewx/view?usp=sharing',
    category: '',
    superteamMember: 'Vietnam',
  },
  {
    order: 16,
    createdAt: '3/21/2023 17:04:07',
    email_id: 'tuanpmhd@gmail.com',
    name: 'Maius Fun',
    description:
      'Maius Fun is a mobile application built on Solana with a seamless UX that allows users to turn photos taken at an IRL event into NFTs for FREE!',
    logoUrl: 'https://cdn.maius.fun/assets/maius_fun_logo.png',
    productUrl: 'https://maius.fun',
    codeUrl: 'https://github.com/Maius-Protocol/maius-fun',
    projectUrls: '',
    teamLeadName: 'Tuan Pham Minh',
    teamLeadEmail: 'tuanpmhd@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/tuanpmhd',
    teamMembersNames: 'Huy Nguyen Quang, Thomas Hoang',
    teamMembersEmails: 'huyryze2419@gmail.com, megatunger@gmail.com',
    teamMembersSocialUrls:
      'https://twitter.com/toilahuy7, https://twitter.com/thomas_ignore',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile, Consumer',
    demoUrl: 'https://vimeo.com/804569135',
    category: '',
    superteamMember: 'Vietnam',
  },
  {
    order: 17,
    createdAt: '3/21/2023 17:09:17',
    email_id: 'zerdest30@gmail.com',
    name: 'PartnerNFT',
    description:
      'PartnerNFT: The social Solana NFT marketplace app for buying, selling, and sharing with partners or friends.',
    logoUrl: '',
    productUrl: 'https://partner-nft-git-master-ahmetzer0.vercel.app',
    codeUrl: 'https://github.com/AhmetZer0/PartnerNFT',
    projectUrls: '',
    teamLeadName: 'Ahmet Zerdeşt Çapik',
    teamLeadEmail: 'zerdest30@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/HesoromiZer0',
    teamMembersNames: 'I am the only one in the team :)',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track:
      'DeFi, Payments, Consumer, Tools & Infrastructure, DAOs and Network States',
    demoUrl: 'https://www.loom.com/share/365cf646ed164858a285e27f8ea01420',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 18,
    createdAt: '3/21/2023 17:10:03',
    email_id: 'cagri058@hotmail.com',
    name: 'Universal SolPay',
    description:
      'Universal SolPay; allows to developers accept Solana payment on their Universal Windows Platfroms applications. (now supports Windows Forms)',
    logoUrl:
      'https://raw.githubusercontent.com/cagrik/USP/master/UspLogo-b.png',
    productUrl: 'https://www.nuget.org/packages/USP',
    codeUrl: 'https://github.com/cagrik/usp',
    projectUrls: '',
    teamLeadName: 'Çağrı',
    teamLeadEmail: 'cagri058@hotmail.com',
    teamLeadSocialUrl: 'https://twitter.com/cagri058',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Payments, Tools & Infrastructure',
    demoUrl: 'https://www.youtube.com/watch?v=Xvy5dSbEqN8',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 19,
    createdAt: '3/21/2023 17:12:11',
    email_id: 'nhqnhq1@gmail.com',
    name: 'Lamas Finance',
    description:
      'Lamas Finance is a true-Dapp-game hub on Solana, providing users with fascinating Dapp games and chances to win massive rewards.',
    logoUrl:
      'https://drive.google.com/file/d/1nKdWmVaPciG02yNwacwHyE-D0RZyxBHV/view?usp=sharing',
    productUrl: 'https://testnet.lamas.co/',
    codeUrl: 'https://github.com/Lamas-Finance-Official',
    projectUrls: '',
    teamLeadName: 'Quang Nguyen',
    teamLeadEmail: 'nhqnhq1@gmail.com',
    teamLeadSocialUrl: 'https://t.me/quatino',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Gaming',
    demoUrl: 'https://www.youtube.com/watch?v=IRot7lJd6z0',
    category: '',
    superteamMember: 'Vietnam',
  },
  {
    order: 20,
    createdAt: '3/21/2023 17:21:54',
    email_id: 'chung.nguyen@metain.io',
    name: 'Demusify',
    description:
      'Demusify is an NFT marketplace for indie music creators to quickly identify and monetize their contents.',
    logoUrl: 'https://i.ibb.co/3YnTfQ3/IMG-1678601613165-001.jpg',
    productUrl: 'https://demusify.xyz',
    codeUrl: 'https://github.com/metain-io/demusify-app',
    projectUrls: '',
    teamLeadName: 'Chung',
    teamLeadEmail: 'chung.nguyen@metain.io',
    teamLeadSocialUrl: 'https://www.linkedin.com/in/ntchung/',
    teamMembersNames: 'Nhan Tran,Hong Luu',
    teamMembersEmails: 'nhan.tran@metain.io,hong.luu@metain.io',
    teamMembersSocialUrls:
      'https://www.linkedin.com/in/tran-nhan-56627076/,https://www.linkedin.com/in/luulamhong/',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DeFi, Consumer',
    demoUrl: 'https://youtu.be/XTXIjNtQpwE',
    category: '',
    superteamMember: 'Vietnam',
  },
  {
    order: 21,
    createdAt: '3/21/2023 17:35:52',
    email_id: 'anishde2007@gmail.com',
    name: 'RayAuth',
    description:
      'Seamless onboarding infra for users and better transaction UX for users on Solana dApps',
    logoUrl:
      'https://api.typeform.com/responses/files/1a8767d5edfefd4cf5b19d0c758c4c31ac4276f71d5294f1b5cc25015ca74223/Logo___bg.png',
    productUrl: 'https://www.rayauth.com/',
    codeUrl: 'https://github.com/AnishDe12020/rayauth',
    projectUrls: '',
    teamLeadName: 'Anish De',
    teamLeadEmail: 'anishde2007@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/AnishDe12020',
    teamMembersNames: 'Apoorv Singh, Sagar Gajare',
    teamMembersEmails: 'apoorvcodes381@gmail.com, sggajare360@gmail.com',
    teamMembersSocialUrls:
      'https://twitter.com/apoorvcodes, https://twitter.com/SagarGajare20',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Consumer, Tools & Infrastructure',
    demoUrl: 'https://www.youtube.com/watch?v=sj0xvahmNd8',
    category: '',
    superteamMember: 'India',
  },
  {
    order: 22,
    createdAt: '3/21/2023 17:57:30',
    email_id: 'hong.luu@metain.io',
    name: 'METAIN',
    description:
      'Tokenized NFTs for real estate, music, startups and crypto projects that are able to deliver real profits for NFT holders.',
    logoUrl:
      'https://drive.google.com/file/d/1Z6uvncGjdJ2mMqbsSeAiMpkTEcvP7WTi/view?usp=sharing',
    productUrl: 'https://metain.app',
    codeUrl:
      'https://github.com/metain-io/code-camp-hackathon/tree/dev?fbclid=IwAR3_k2HoBoOGe3u3JBw_i5Mx2kW_vc39qRIo1cusEJ4r_0MUElfuK9MPiGs',
    projectUrls: '',
    teamLeadName: 'Nhan Tran ',
    teamLeadEmail: 'nhan.tran@metain.io ',
    teamLeadSocialUrl: 'https://www.linkedin.com/in/tran-nhan-56627076/',
    teamMembersNames: 'Hong Luu, Chung Nguyen ',
    teamMembersEmails: 'hong.luu@metain.io, chung.nguyen@metain.io ',
    teamMembersSocialUrls:
      'https://www.linkedin.com/in/luulamhong/, https://www.linkedin.com/in/ntchung/',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DeFi, Payments, Consumer, DAOs and Network States',
    demoUrl: 'https://youtu.be/J3jldiiml08',
    category: '',
    superteamMember: 'Vietnam',
  },
  {
    order: 23,
    createdAt: '3/21/2023 17:58:52',
    email_id: 'tufan@rpc.ag',
    name: 'RPC Aggregator',
    description: 'Homepage for Blockchain Infrastructure',
    logoUrl: 'https://rpc.ag/images/rpc-logo.png',
    productUrl: 'https://docs.rpc.ag/',
    codeUrl: 'https://github.com/rpc-ag',
    projectUrls: '',
    teamLeadName: 'Tufan',
    teamLeadEmail: 'tufan@rpc.ag',
    teamLeadSocialUrl: 'https://twitter.com/tfnyldrm',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Tools & Infrastructure',
    demoUrl: '',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 24,
    createdAt: '3/21/2023 18:38:48',
    email_id: 'tinftsol@gmail.com',
    name: 'tinft',
    description:
      'We are building a project which will help you to explore the world of NFTs in a new way.\n\nIt’s easy and fun to find new NFTs! Use Swipe Right if you like NFT and left if not.',
    logoUrl:
      'https://pbs.twimg.com/profile_images/1632582677663555584/aNgWnh_R_400x400.jpg',
    productUrl: 'https://tinft-sol.herokuapp.com/',
    codeUrl: '',
    projectUrls: '',
    teamLeadName: 'nicolass',
    teamLeadEmail: 'bagdeyv@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/nicolass_sa',
    teamMembersNames: 'nicolass,e.streshnev,avychev',
    teamMembersEmails:
      'bagdeyv@gmail.com,swwwifty@gmail.com,avychev.work@gmail.com',
    teamMembersSocialUrls:
      'https://www.linkedin.com/in/uladzislau-bahdzei/,https://www.linkedin.com/in/andrewvychev/,https://www.linkedin.com/in/egor-streshnev/',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile',
    demoUrl: 'https://www.youtube.com/watch?v=wldCINZrRU4',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 25,
    createdAt: '3/21/2023 18:44:43',
    email_id: 'murat.unsal@gmail.com',
    name: 'Budget Blocks',
    description:
      'Budget Blocks is a blockchain-based platform that allows companies and individuals to create and manage budgets, as well as make payments, and plan staking operations according to those budgets.',
    logoUrl:
      'https://drive.google.com/file/d/1SbAedWbU75LasTlb8SodSN2CK0P6da8y/view?usp=sharing',
    productUrl: 'https://twitter.com/budgetblocks',
    codeUrl: 'https://github.com/BudgetBlocksHackathon',
    projectUrls: '',
    teamLeadName: 'Murat Ünsal',
    teamLeadEmail: 'murat.unsal@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/kubarist',
    teamMembersNames: 'Cengiz Kılıçaslan, Göktuğ Oğuz Güngör, Emrecan Üzüm',
    teamMembersEmails:
      'cengiz.kilicaslan3434@gmail.com, goguzgungor59@gmail.com, uzumemrecan@gmail.com',
    teamMembersSocialUrls:
      'https://twitter.com/cengiz_kaslan, http://t.me/goktugoguz, https://twitter.com/RiluanethNFT',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile, DeFi, Payments, Consumer, Tools & Infrastructure',
    demoUrl: 'https://youtu.be/EzfNBc7QDG4',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 26,
    createdAt: '3/21/2023 19:00:43',
    email_id: 'ali.erdem.karacay@gmail.com',
    name: 'ResWiki',
    description:
      'Wikipedia in blockchain. All articles are stored on blockchain and accessed with transactions.',
    logoUrl:
      'https://drive.google.com/file/d/1MKLZeCt0Y6i1Z-J5yX7HJ21vb_joVLks/view?usp=share_link',
    productUrl: '',
    codeUrl: 'https://github.com/Arsivnet/ResWiki',
    projectUrls: '',
    teamLeadName: 'Ali Erdem Karaçay',
    teamLeadEmail: 'ali.erdem.karacay@proton.me',
    teamLeadSocialUrl: '',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DAOs and Network States',
    demoUrl: 'https://youtu.be/qxaW17tm-ec',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 27,
    createdAt: '3/21/2023 19:23:52',
    email_id: 'aygdgms.zeynep@gmail.com',
    name: 'SoLucky Fighters',
    description:
      'With the power of gamified interface, we are creating a platform where users can play card games.But know the lucky ones are chosen from the metadatas. \n',
    logoUrl:
      'https://r.resimlink.com/OxHV5s.png?v=f9bb06d4a3ce5951f386a7c3ffc44b2e',
    productUrl: '',
    codeUrl: 'https://github.com/eneskeremturan/buildspace-solana',
    projectUrls: '',
    teamLeadName: 'Beyazit Karinca',
    teamLeadEmail: 'beyazitkarinca96@gmail.com',
    teamLeadSocialUrl: 'https://linkedin.com/in/beyazit-karinca',
    teamMembersNames: 'Zeynep Aydogmus, Beyazit Karinca, Kemal Gurgen',
    teamMembersEmails: 'aydgms.zeynep@gmail.com , gurgenk022@gmail.com',
    teamMembersSocialUrls:
      'linkedin.com/in/kemal-gurgen , linkedin.com/in/zeynep-aydogmus',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Gaming, NFT',
    demoUrl: 'https://www.loom.com/share/1ec6a57b654a42639f462a889817218c',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 28,
    createdAt: '3/21/2023 19:45:59',
    email_id: 'leo@console.so',
    name: 'Mochi Pay',
    description:
      'With the aim to bring the to everyone, Mochi Bot promises to make cryptocurrency sending and receiving simple, even for who are not wallet-equipped!',
    logoUrl:
      'https://drive.google.com/file/d/1fEVhieXA045HocZWWIfVgqwi1uKVDP4C/view?usp=sharing',
    productUrl: 'https://mochi.gg/',
    codeUrl: 'https://github.com/consolelabs/mochi-pay-api',
    projectUrls: '',
    teamLeadName: 'Nguyen Hoang Huy',
    teamLeadEmail: 'hoanghuy2908@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/_hnh2908',
    teamMembersNames:
      'Long "Leo" Pham,Hien-Minh Nguyen-Le, Khoi Ngo Trong,Anh Nguyen Hoang',
    teamMembersEmails:
      'leo@console.so,minhnlh19@gmail.com,ngotrongkhoi112@gmail.com,nguyenhoanganh0772@gmail.com',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DeFi, Payments',
    demoUrl:
      'https://drive.google.com/file/d/17NB6JfmoW5XCA_7CefIyxKjVe_FMdwAK/view?usp=share_link',
    category: '',
    superteamMember: 'Vietnam',
  },
  {
    order: 29,
    createdAt: '3/21/2023 19:52:18',
    email_id: 'uci.onur@gmail.com',
    name: 'Solauth',
    description:
      'We are building one-place sign in platform on Solana. Where users can build their Solana profiles which have social recovery features. Then connect to applications with their one Solana profile.',
    logoUrl: 'https://www.solauth.xyz/logo.svg',
    productUrl: 'https://www.solauth.xyz/',
    codeUrl: 'https://github.com/onuruci/solauth',
    projectUrls: '',
    teamLeadName: 'Onur Yüce',
    teamLeadEmail: 'uci.onur@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/Koda2136',
    teamMembersNames: 'Tunahan Dündar,Şevket Pala',
    teamMembersEmails: '',
    teamMembersSocialUrls:
      'https://twitter.com/thlikelymdiorum,https://twitter.com/marcusm4ximus',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Consumer, Tools & Infrastructure',
    demoUrl: 'https://www.youtube.com/watch?v=xHB14slYjGM',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 30,
    createdAt: '3/21/2023 19:55:25',
    email_id: 'elifnurisiikk@gmail.com',
    name: 'SOLODORO',
    description:
      'SOLODORO the best motivational course platform for those out there who want to be web3 developers.',
    logoUrl: 'https://www.dropbox.com/s/sgag2yygkw0qdzg/30-SOLODORO.png?dl=1',
    productUrl: '',
    codeUrl: 'https://github.com/ElifnurIsik/solodoro',
    projectUrls: '',
    teamLeadName: 'Enes Kerem Turan',
    teamLeadEmail: 'eneskeremturan@gmail.com ',
    teamLeadSocialUrl: 'https://www.linkedin.com/in/eneskeremturan/',
    teamMembersNames: 'Kerem Büker,Elif Nur Işık',
    teamMembersEmails: 'bukerkerem@gmail.com,elifnurisiikk@gmail.com',
    teamMembersSocialUrls:
      'https://www.linkedin.com/in/bukerkerem/,https://www.linkedin.com/in/elifnurisiikk/',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DeFi, Consumer',
    demoUrl: 'https://www.loom.com/share/03566aabddcb4b73b463b768f71188e6',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 31,
    createdAt: '3/21/2023 19:55:56',
    email_id: 'yyolcu634@gmail.com',
    name: 'RivalZ',
    description:
      'It is a kind of fantastic football game project which includes different mini games',
    logoUrl: 'https://i.imgur.com/42NUjFw.png',
    productUrl: 'https://www.rivalz.app/',
    codeUrl: 'https://github.com/rivalz-football',
    projectUrls: '',
    teamLeadName: 'RivalZ',
    teamLeadEmail: 'tolgaand@yandex.com',
    teamLeadSocialUrl: '',
    teamMembersNames:
      'Tolga Çağlayan, Yusuf Yolcu, Barış Kaş, Mehmet Kama, Burak Aksu',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Gaming',
    demoUrl: 'https://www.rivalz.app/dashboard',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 32,
    createdAt: '3/21/2023 20:35:35',
    email_id: 'mailberkayoztunc@gmail.com',
    name: 'Spark Online',
    description:
      'Spark Online is a web3 token-gated marketing platform that enables nano- and micro-influencers to monetize their social media presence through content creation and engagement.',
    logoUrl: 'https://sparkonline.xyz/assets/images/logos.png',
    productUrl: 'https://www.youtube.com/watch?v=czzK__4bj-s&t=195s',
    codeUrl: 'https://gitlab.com/geniousoft/sparkleapi',
    projectUrls: '',
    teamLeadName: 'Berkay Öztunç',
    teamLeadEmail: 'mailberkayoztunc@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/WhiteMoonDev',
    teamMembersNames:
      'Alper Sendan, Ömer Temel, Emre Arslan , Utku Özen, Murat Ünsal',
    teamMembersEmails:
      'alpersendan@gmail.com,mailomertemel@gmail.com,yemrearslann@gmail.com, utkuozen1993@gmail.com,murat.unsal@gmail.com',
    teamMembersSocialUrls:
      'https://twitter.com/casparstein,https://twitter.com/omr_dev,https://twitter.com/W41N1ZxA7Ct9,https://twitter.com/kubarist,https://twitter.com/utkuozen93,https://twitter.com/kubarist',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Payments, Consumer, Tools & Infrastructure',
    demoUrl: '',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 33,
    createdAt: '3/21/2023 20:38:53',
    email_id: 'carlos@triggr.app',
    name: 'Triggr',
    description: 'No-code automation platform to connect anything on Solana',
    logoUrl:
      'https://shdw-drive.genesysgo.net/CxNqS1ndxKXb8HGoS52CVEfDjfA9Jmay4YsUFrbZ1CxR/newTriggrLogo.png',
    productUrl: ' https://triggr.app/',
    codeUrl: '',
    projectUrls: '',
    teamLeadName: 'Carlos',
    teamLeadEmail: 'carlos@triggr.app',
    teamLeadSocialUrl: 'https://twitter.com/Carlos_0x',
    teamMembersNames: 'Walid,Marco',
    teamMembersEmails: '',
    teamMembersSocialUrls:
      'https://twitter.com/ifulido,https://twitter.com/olistic42',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Tools & Infrastructure',
    demoUrl: 'https://www.youtube.com/watch?v=xcgKP_fKLLw&ab_channel=Triggr',
    category: '',
    superteamMember: 'Germany',
  },
  {
    order: 34,
    createdAt: '3/21/2023 20:41:24',
    email_id: 'snceyd@gmail.com',
    name: 'Time of Life',
    description:
      'Time of Life provides progressive, and affordable healthcare.',
    logoUrl:
      'https://drive.google.com/file/d/1emEW8oJzhbkVtPwmcmnu_Xh8bSLL2wRg/view?usp=sharing',
    productUrl: 'https://www.timeof.life/',
    codeUrl: 'https://github.com/tomiece317/TimeofLifeHackathon',
    projectUrls: '',
    teamLeadName: 'Ceyda',
    teamLeadEmail: 'snceyd@gmail.com',
    teamLeadSocialUrl: 'https://www.linkedin.com/in/ceyda-esen/',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Payments, Consumer',
    demoUrl: 'https://prezi.com/v/view/VOg6wXT9yzz5gDukMobb/',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 35,
    createdAt: '3/21/2023 20:43:58',
    email_id: 'sasha@shpota.com',
    name: 'sol4k',
    description: 'Kotlin, JVM, and Android client for Solana',
    logoUrl:
      'https://pbs.twimg.com/profile_images/1636279263769812997/crAMHImu_400x400.jpg',
    productUrl: 'https://sol4k.org',
    codeUrl: 'https://github.com/sol4k/sol4k',
    projectUrls: '',
    teamLeadName: 'Sasha Shpota',
    teamLeadEmail: 'sasha@shpota.com',
    teamLeadSocialUrl: 'https://github.com/Shpota',
    teamMembersNames: '-',
    teamMembersEmails: '-',
    teamMembersSocialUrls: '-',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Tools & Infrastructure',
    demoUrl: 'https://github.com/sol4k/sol4k-examples',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 36,
    createdAt: '3/21/2023 20:44:03',
    email_id: 'arslanturk@gmail.com',
    name: 'Dome Metamars',
    description: 'Dome is a blockchain based city building game in metaverse.',
    logoUrl: 'https://www.domemetamars.com/assets/logo.64058ee9.png',
    productUrl: 'https://www.domemetamars.com/',
    codeUrl: 'https://github.com/DomeMetamars',
    projectUrls: '',
    teamLeadName: 'Tarık Arslantürk',
    teamLeadEmail: 'arslanturk@gmail.com',
    teamLeadSocialUrl: 'https://youtube.com/c/Sinetech1',
    teamMembersNames:
      'Sinan Kaya,Ediz Kepir,Arda Biçen,Ahmet Bozkurt,Eren Akçakaya,Alper Tanrısever,Fatih Akça,Ece Türkyılmaz,Kerem Irgan,Faruk Uzun',
    teamMembersEmails:
      'snnkaya@gmail.com,edikez@gmail.com,arda005bicen@gmail.com,bozkurtahmet65@hotmail.com,ereneren_eren@hotmail.com,alpertnrsvr@gmail.com,coinocracy@gmail.com,eceturkyilmaz91@gmail.com,kirgan@adeks.net,omerfauzun@outlook.com',
    teamMembersSocialUrls:
      'linkedin.com/in/sinan-kaya-0300b3228,linkedin.com/in/ediz-kepir,linkedin.com/in/mustafa-arda-biçen-106b76146,linkedin.com/in/muhammed-eren-akçakaya-8a7524208,linkedin.com/in/alpertnrsvr/,linkedin.com/in/muratakca42,linkedin.com/in/eceturkyilmaz3d,linkedin.com/in/kerem-i-8a018520,linkedin.com/in/ömer-faruk-uzun-7480b9244',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Gaming',
    demoUrl: 'https://youtu.be/0EhT8fSYHR4',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 37,
    createdAt: '3/21/2023 20:54:20',
    email_id: 'henrypham.po@gmail.com',
    name: 'SolClan',
    description:
      'SolClan is a web3 investment platform that lets people create clans and invest together in early-stage projects.  ',
    logoUrl:
      'https://drive.google.com/file/d/17G0sBWRXU2zVF6FkMd_mMVGChwV1KfUn/view?usp=share_link',
    productUrl: 'https://solclan.xyz/',
    codeUrl: 'https://github.com/brolab-io/solana-solclan',
    projectUrls: '',
    teamLeadName: 'Henry Pham',
    teamLeadEmail: 'henrypham.po@gmail.com',
    teamLeadSocialUrl: 'https://www.facebook.com/cuong.phamvu.7796',
    teamMembersNames: 'Leo Phạm, Phú Huỳnh, Trọng Công Nguyễn, Đỗ Tín',
    teamMembersEmails: 'tronginc@gmail.com',
    teamMembersSocialUrls:
      'https://www.facebook.com/hongthaipro,https://www.facebook.com/long.phu,https://www.facebook.com/tronginc',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile, DeFi, DAOs and Network States',
    demoUrl:
      'https://docs.google.com/presentation/d/1FyT9YO6xVIyzOEiYHCb2RfEIMZWqMCI5es8jxM1Vk10/edit#slide=id.p',
    category: '',
    superteamMember: 'Vietnam',
  },
  {
    order: 38,
    createdAt: '3/21/2023 21:07:37',
    email_id: 'kiraomgamer@gmail.com',
    name: 'PaySol',
    description:
      'App that is for wallet and does the basic functions of a wallet as well as sending money directly to users and being able to split accounts and pay with a click.',
    logoUrl:
      'https://drive.google.com/file/d/1c87w2fr0b_EG6D_5QQ0QNY_ekklzDgYI/view?usp=share_link',
    productUrl: 'https://paysol.kirabel.com/',
    codeUrl:
      'https://github.com/KiraBelak/PaySol---Etherfuse-2023---hackathon.git',
    projectUrls: '',
    teamLeadName: 'Kaleb Rodriguez',
    teamLeadEmail: 'kiraomgamer@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/KiraBelak',
    teamMembersNames: 'Lizbeth Hernandez',
    teamMembersEmails: 'L19012390@chihuahua2.tecnm.mx',
    teamMembersSocialUrls: 'https://www.facebook.com/Vsherpoetamaldita',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile, DeFi, Payments',
    demoUrl: 'https://youtu.be/blWdfX0N5Z8',
    category: '',
    superteamMember: 'Mexico',
  },
  {
    order: 39,
    createdAt: '3/21/2023 21:20:37',
    email_id: 'berkingurcan@gmail.com',
    name: 'Crypto Corsairs',
    description: 'Anchor Learning platform',
    logoUrl:
      'https://drive.google.com/file/d/1_caEgM1U3ILUzb76_Ugl54OGeoZRRwBJ/view?usp=sharing',
    productUrl: 'https://cryptocorsairs.vercel.app/',
    codeUrl: 'https://github.com/berkingurcan/crypto-corsairs.io',
    projectUrls: '',
    teamLeadName: 'Berkin Gürcan',
    teamLeadEmail: 'berkingurcan@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/cryptocorsairs',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Tools & Infrastructure',
    demoUrl: 'https://cryptocorsairs.vercel.app/',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 40,
    createdAt: '3/21/2023 21:41:53',
    email_id: 'antinucleuss@gmail.com',
    name: 'Find it',
    description:
      'Find it is a decentralized mobile game. Users can compete each other and collet Nfts.',
    logoUrl: 'https://www.dropbox.com/s/pdeili3vx6k0x4p/Logo.png?dl=1',
    productUrl: 'https://github.com/antinucleus/findit/releases/tag/v0.1.2',
    codeUrl: 'https://github.com/antinucleus/findit',
    projectUrls: '',
    teamLeadName: 'Ömer Faruk Bağcı',
    teamLeadEmail: 'antinucleuss@gmail.com',
    teamLeadSocialUrl: 'https://www.linkedin.com/in/omerfarukbagci/',
    teamMembersNames: 'Ömer Faruk Bağcı',
    teamMembersEmails: 'antinucleuss@gmail.com',
    teamMembersSocialUrls: 'https://www.linkedin.com/in/omerfarukbagci/',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile, Gaming',
    demoUrl:
      'https://drive.google.com/drive/folders/1DXwuySCZVb_f_ja67kBoewGf5zyPwsRN?usp=share_link',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 41,
    createdAt: '3/21/2023 21:49:00',
    email_id: 'tas7095@gmail.com',
    name: 'Lixen',
    description:
      "Lixen's goal is to have a volatile structure that combines community, artificial intelligence and NFT, algorithm-based Blockchain games.",
    logoUrl:
      'https://pbs.twimg.com/profile_images/1632174769129893888/DEPSLN3p_400x400.jpg',
    productUrl: 'https://twitter.com/lixenlabs?t=iBAQgZNa808BZmP3nebztQ&s=09',
    codeUrl: 'https://github.com/lixenn',
    projectUrls: '',
    teamLeadName: 'Emre taş',
    teamLeadEmail: 'tas7095@gmail.com',
    teamLeadSocialUrl:
      'https://twitter.com/Emretas1459?t=UxR8e6axi40y2zkWOWjJKA&s=09',
    teamMembersNames: 'Elif Vural ',
    teamMembersEmails: 'elifvural03@gmail.com',
    teamMembersSocialUrls:
      'https://twitter.com/ElifV21?t=CpRUFfe1SRo6XTYy7VHv1A&s=09',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DeFi, Payments, Gaming, DAOs and Network States',
    demoUrl: 'https://youtu.be/qtwUAE2wAnI',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 42,
    createdAt: '3/21/2023 22:48:19',
    email_id: 'ekcmuhammed08@gmail.com',
    name: 'Monocle NFT Viewer',
    description:
      'Monocle is an open source NFT Explorer project, \nyou can view all the nfts a wallet has with it.\n',
    logoUrl:
      'https://drive.google.com/file/d/1fIA1-FG6lZ68txIbYbhDmQ98inif0KRa/view',
    productUrl: 'https://monocle.vercel.app/',
    codeUrl: 'https://github.com/ekcmuhammed08/monocle-nft-viewer',
    projectUrls: '',
    teamLeadName: 'Muhammed Ekici',
    teamLeadEmail: 'ekcmuhammed08@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/metamethyll',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Consumer, Tools & Infrastructure',
    demoUrl: 'https://www.loom.com/share/6c9c99bc9bf84b84abdef4b1667b0603',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 43,
    createdAt: '3/21/2023 22:59:40',
    email_id: 'elifvural03@gmail.com',
    name: 'Solixen',
    description:
      'We build flexible and secure tools for creating, managing, and scaling DAOs, allowing everyone to experiment with governance at the speed of software.',
    logoUrl:
      'https://pbs.twimg.com/profile_images/1634475076572659712/wW3Y9g62_400x400.jpg',
    productUrl: 'https://twitter.com/Solixenlabs',
    codeUrl: 'https://github.com/solixenn',
    projectUrls: '',
    teamLeadName: 'Elif',
    teamLeadEmail: 'elifvural03@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/ElifV21',
    teamMembersNames: 'Emre',
    teamMembersEmails: 'tas7095@gmial.com, elifvural03@gmail.com',
    teamMembersSocialUrls:
      'https://twitter.com/ElifV21,https://twitter.com/Emretas1459?t=UxR8e6axi40y2zkWOWjJKA&s=09\n',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DeFi',
    demoUrl: 'https://www.youtube.com/watch?v=IN4iqWIt_K0&t=243s',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 44,
    createdAt: '3/22/2023 4:20:51',
    email_id: 'vadimlarintech@gmail.com',
    name: 'SolCheck',
    description: 'B2B ML scam detection service',
    logoUrl: 'https://i.ibb.co/GnQqdxt/high-Screen-transformed-512px.png',
    productUrl: 'https://solcheck.gitbook.io/docs-of-solcheck/',
    codeUrl: '',
    projectUrls: '',
    teamLeadName: 'Vadim Larin',
    teamLeadEmail: 'vadimlarintech@gmail.com',
    teamLeadSocialUrl: 'https://www.linkedin.com/in/vadim-larin/ ',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Tools & Infrastructure',
    demoUrl: 'https://www.loom.com/share/c19a3f7aacac40f1b4b2fe3b3b0061b0',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 45,
    createdAt: '3/22/2023 4:42:52',
    email_id: 'orionadler7575@gmail.com',
    name: 'Bunkr',
    description:
      'Bunkr provides users on Solana the option to protect assets with an extra layer of security. Specifically with TOTPs (Time Based Onetime Passwords) that are compatible with web2 authentication apps.',
    logoUrl: 'https://avatars.githubusercontent.com/u/127030674?s=200&v=4',
    productUrl: 'https://getbunkr.xyz',
    codeUrl: 'https://github.com/Bunkr-On-Chain-2FA',
    projectUrls: '',
    teamLeadName: 'Orion (@_SirIsaac',
    teamLeadEmail: 'orionadler7575@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/_SirIsaac',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Consumer, Tools & Infrastructure',
    demoUrl: 'https://www.loom.com/share/e2da2ce9e58c441c8bbf9d1ee57c21b9',
    category: '',
    superteamMember: 'Germany',
  },
  {
    order: 46,
    createdAt: '3/22/2023 4:58:10',
    email_id: 'temi@aztemi.com',
    name: 'Solana Pay for WordPress and WooCommerce',
    description:
      'A payment gateway built for WooCommerce online stores to accept payments in USDC and SOL through Solana Pay.',
    logoUrl: '',
    productUrl: 'https://solana-pay-demo.juxdan.io/',
    codeUrl: 'https://github.com/t4top/solana-pay-for-woocommerce',
    projectUrls: '',
    teamLeadName: 't4top',
    teamLeadEmail: 'temi@aztemi.com',
    teamLeadSocialUrl: 'https://github.com/t4top',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile, Payments, Consumer',
    demoUrl: '',
    category: '',
    superteamMember: 'Germany',
  },
  {
    order: 47,
    createdAt: '3/22/2023 5:10:50',
    email_id: 'nguyenhoangduc0701@gmail.com',
    name: 'Akather',
    description:
      'We are building deep simulation learning infrastructure platform on metaverse',
    logoUrl: 'https://i.ibb.co/LP3QbKS/logo-akather-bigsize.png',
    productUrl: 'https://www.akather.io',
    codeUrl: 'https://github.com/Akather-io/akather-solana',
    projectUrls: '',
    teamLeadName: 'Nguyen Hoang Duc',
    teamLeadEmail: 'nguyenhoangduc0701@gmail.com',
    teamLeadSocialUrl: 'https://www.linkedin.com/in/duc-nguyen-597123165/',
    teamMembersNames:
      'Pham Hong Thai,Huynh Long Phu,Le Thanh Minh,Tran Minh Hanh',
    teamMembersEmails:
      'phthai.dev@gmail.com,longphu257@gmail.com,minh.niithoasen@gmail.com,brainstorm.tran@gmail.com\n',
    teamMembersSocialUrls:
      'https://www.linkedin.com/in/leo-pham-1208,https://www.facebook.com/long.phu,https://www.linkedin.com/in/min-lee-min-lee-36a97574/,https://www.linkedin.com/in/hanhtran437/',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Tools & Infrastructure, Metaverse ',
    demoUrl: 'https://youtu.be/aPOmjtMS-yw',
    category: '',
    superteamMember: 'Vietnam',
  },
  {
    order: 48,
    createdAt: '3/22/2023 5:39:36',
    email_id: 'tarik.bugra@xoxgames.io',
    name: 'XoX Games - Thieves Gallery',
    description: 'We are the pioneers of indie web3 gaming!',
    logoUrl: 'https://godijital.net/bugra/images/site/logo.png',
    productUrl: 'https://godijital.net/bugra',
    codeUrl: '',
    projectUrls: '',
    teamLeadName: 'Tarık Buğra Kahraman',
    teamLeadEmail: 'tarik.bugra@xoxgames.io',
    teamLeadSocialUrl: 'https://www.linkedin.com/in/tarikbugra/',
    teamMembersNames:
      'Yusuf Turgut, Umut Can Gökçeli, Esin Karabenli, Ege Yıldırım, Kerem Aktuna, Yağız Erdemir, Ozan Birses, Celal Güler',
    teamMembersEmails:
      'Yusuf.Turgut@xoxgames.io, Umut.Gökçeli@xoxgames.io, Esin.Karabenli@xoxgames.io, Ege.Yıldırım@xoxgames.io, Kerem.Aktuna@xoxgames.io, Yağız.Erdemir@xoxgames.io, Ozan.Birses@xoxgames.io, Celal.Güler@xoxgames.io',
    teamMembersSocialUrls: 'https://www.linkedin.com/company/xoxgames',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Gaming',
    demoUrl: 'https://www.mvp.xoxgames.io/',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 49,
    createdAt: '3/22/2023 6:23:58',
    email_id: 'jamesnguyen@icrosschain.io',
    name: 'iCrosschain',
    description:
      'iCrosschain is speciallized designing for cross-chain transactions and aggregated transactions, allowing all users to enjoy lower transaction fees and lower slippage to complete the assets exchange.',
    logoUrl:
      'https://drive.google.com/file/d/15YbbAbwYPVESpmtb16Px5p7NFFtQMPjZ/view',
    productUrl: 'https://icrosschain.io/',
    codeUrl: 'https://github.com/spike-inu',
    projectUrls: '',
    teamLeadName: 'James Nguyen',
    teamLeadEmail: 'jamesnguyen@icrosschain.io',
    teamLeadSocialUrl: '',
    teamMembersNames: 'Hugo Tran, Tommy Nguyen, Katy Tran, Do Nhi, Tom Nguyen',
    teamMembersEmails:
      'hungtran@icrosschain.io, thanhnp@icrosschain.io, trangnguyen@icrosschain.io, donhi@icrosschain.io, tomnguyen@icrosschain.io',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile, DeFi, Tools & Infrastructure',
    demoUrl: '',
    category: '',
    superteamMember: 'Vietnam',
  },
  {
    order: 50,
    createdAt: '3/22/2023 9:14:23',
    email_id: 'hub3ee@gmail.com',
    name: 'Hub3',
    description:
      'Hub3 is a social media platform that connects users based on demographics and interest with the vision of Home for WEB3.',
    logoUrl:
      'https://pbs.twimg.com/profile_images/1619589144753147904/tEAQfy5c_400x400.jpg',
    productUrl: 'https://hub3.ee',
    codeUrl: '',
    projectUrls: '',
    teamLeadName: 'Furkan Demir',
    teamLeadEmail: 'hub3ee@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/SolBridgeNW',
    teamMembersNames: 'Oğuzhan Karadayı,\nBerkay Özdemir,\nEren Yılmaz',
    teamMembersEmails: 'hello@hub3.ee',
    teamMembersSocialUrls:
      'https://twitter.com/MrPerrex,\nhttps://twitter.com/tsaadi_,\nhttps://twitter.com/lipsum30',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Consumer, Tools & Infrastructure, DAOs and Network States',
    demoUrl: '',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 51,
    createdAt: '3/22/2023 9:27:12',
    email_id: 'hub3ee@gmail.com',
    name: 'MailX',
    description:
      'Decentralized, end to end encrypted, transactionless, open source, and free email service.',
    logoUrl:
      'https://pbs.twimg.com/profile_images/1633201227528896520/ic7jzW3k_400x400.jpg',
    productUrl: 'https://mailx.to/',
    codeUrl: '',
    projectUrls: '',
    teamLeadName: 'Furkan Demir',
    teamLeadEmail: 'hub3ee@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/SolBridgeNW',
    teamMembersNames: 'Oğuzhan Karadayı,\nBerkay Özdemir,\nEren Yılmaz',
    teamMembersEmails: '',
    teamMembersSocialUrls:
      'https://twitter.com/MrPerrex,\nhttps://twitter.com/tsaadi_,\nhttps://twitter.com/lipsum30',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Consumer, Tools & Infrastructure',
    demoUrl:
      'https://drive.google.com/file/d/1FFdgZ0iYPcS97vbOExzgoTIL5Jg9ssyZ/view?usp=sharing',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 52,
    createdAt: '3/22/2023 11:50:20',
    email_id: 'andresaguilar.exe@gmail.com',
    name: 'EzTicket',
    description:
      'We are creating NFTickets for events and a platform for create and manage events',
    logoUrl: '',
    productUrl: 'https://ezticket.vercel.app/',
    codeUrl: 'https://github.com/Avzolem/ezticket',
    projectUrls: '',
    teamLeadName: 'Andrés Aguilar',
    teamLeadEmail: 'andresaguilar.exe@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/avsolem',
    teamMembersNames: 'Ramon Najera',
    teamMembersEmails: 'rnajera@uach.mx',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile, Payments, Consumer',
    demoUrl: 'https://ezticket.vercel.app/slideck',
    category: '',
    superteamMember: 'Mexico',
  },
  {
    order: 53,
    createdAt: '3/22/2023 17:17:21',
    email_id: 'atahan03@hotmail.com',
    name: 'SCOFL',
    description:
      'SCOFL is a platform that merges freelancer system and fundraising system.You can fund projects you liked or you can complate tasks as developer to contribute the project. ',
    logoUrl:
      'https://drive.google.com/file/d/1_iY1t0VteOIuh6DCXZFbXBRi8QHojAFd/view',
    productUrl: '',
    codeUrl: 'https://github.com/atahanyild/SCOFL',
    projectUrls: '',
    teamLeadName: 'Atahan YILDIRIM',
    teamLeadEmail: 'atahan03@hotmail.com',
    teamLeadSocialUrl: 'https://www.linkedin.com/in/atahan-yıldırım-1075831b1/',
    teamMembersNames: 'Ediz ZÜM,Hasan Kutay SARI,Emin KOTAN',
    teamMembersEmails:
      'ediz.zum@hotmail.com,h.kutay.1@gmail.com,eminkotan@gmail.com',
    teamMembersSocialUrls:
      'https://www.linkedin.com/in/ediz-zum/,https://www.linkedin.com/in/hasan-kutay-sarı-0a5048223/,https://www.linkedin.com/in/eminkotan/',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track:
      'Mobile, DeFi, Payments, Consumer, Tools & Infrastructure, Gaming, DAOs and Network States',
    demoUrl: 'https://www.loom.com/share/3a189fd069e7478fadbb46a1e424f114',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 54,
    createdAt: '3/22/2023 17:16:39',
    email_id: 'atahan03@hotmail.com',
    name: 'SMACOFL',
    description:
      'SMACOFL provides Freelancer developers and Project owners to find each other.This is a decentrealized alternative to traditional websites because smart contract runs the system instead of middleman.',
    logoUrl:
      'https://drive.google.com/file/d/14y1b9xnRP19NG5urY8NSmoRXRDS-pf4H/view',
    productUrl: '',
    codeUrl: 'https://github.com/atahanyild/SMACOFL',
    projectUrls: '',
    teamLeadName: 'Atahan Yıldırım',
    teamLeadEmail: 'atahan03@hotmail.com',
    teamLeadSocialUrl: 'https://www.linkedin.com/in/atahan-yıldırım-1075831b1/',
    teamMembersNames: 'Ediz Züm,Hasan Kutay Sarı,Emin Kotan',
    teamMembersEmails:
      'ediz.zum@hotmail.com,h.kutay.1@gmail.com,eminkotan@gmail.com',
    teamMembersSocialUrls:
      'https://www.linkedin.com/in/ediz-zum/,https://www.linkedin.com/in/hasan-kutay-sarı-0a5048223/,https://www.linkedin.com/in/eminkotan/',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track:
      'Mobile, DeFi, Payments, Consumer, Tools & Infrastructure, Gaming, DAOs and Network States',
    demoUrl: 'https://www.loom.com/share/58bae4af77aa410492e13eee6f0d8582',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 55,
    createdAt: '3/22/2023 19:22:57',
    email_id: 'adamborcany@gmail.com',
    name: 'SolLightning',
    description:
      'Buliding trustless bridge between Solana and Bitcoin (on-chain and lightning network) to allow anyone to receive and send bitcoin from/to their solana wallet!',
    logoUrl:
      'https://drive.google.com/file/d/1srN-_-xYXqfRoYu1JXph81kCwwVrSZts/view',
    productUrl: '',
    codeUrl: 'https://github.com/adambor/SolLightning-readme',
    projectUrls: '',
    teamLeadName: 'Adam Borčány',
    teamLeadEmail: 'adamborcany@gmail.com',
    teamLeadSocialUrl:
      'https://www.linkedin.com/in/adam-bor%C4%8D%C3%A1ny-151176165/',
    teamMembersNames: 'Adam Borčány,Sylvie Durach,Caspar Huisman',
    teamMembersEmails:
      'adamborcany@gmail.com,sylvie@gethopa.com,caspar@gethopa.com',
    teamMembersSocialUrls:
      'https://www.linkedin.com/in/adam-bor%C4%8D%C3%A1ny-151176165/,https://www.linkedin.com/in/sylviadurach/,https://www.linkedin.com/in/casparhuisman/',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile, DeFi, Payments, Tools & Infrastructure',
    demoUrl: 'https://www.youtube.com/watch?v=ennMMSyMooA',
    category: '',
    superteamMember: 'Germany',
  },
  {
    order: 56,
    createdAt: '3/23/2023 10:44:35',
    email_id: 'zang@stormgate.io',
    name: 'Walless',
    description:
      'Walless is the first web3 sandbox-wallet with embedded dApps, simplified onboarding, unified cross-chain interface. This revolutionizes crypto wallets and enables endless possibilities for builders.',
    logoUrl:
      'https://drive.google.com/file/d/1z3Qk5vVyAJlbvsK92V9Ohosn6LD6uuMM/view',
    productUrl: 'https://walless.io/',
    codeUrl: 'https://github.com/cocrafts/walless',
    projectUrls: '',
    teamLeadName: 'Son Le',
    teamLeadEmail: 'atem@stormgate.io',
    teamLeadSocialUrl: 'https://www.linkedin.com/in/cloudle/',
    teamMembersNames:
      'Zang,Linh Pham,Tuan Tran,Chloe Keith,Tan Le,Hieu Nguyen,Minh Pham',
    teamMembersEmails:
      'zang@stormgate.io,linhpham.ptdl@gmail.com,1414439@gmail.com,lhngoc115@gmail.com,tanlethanh8266@gmail.com,dev.ngtronghieu@gmail.com,hadtnt71@gmail.com',
    teamMembersSocialUrls:
      'https://www.linkedin.com/in/giangdang0115/,https://www.linkedin.com/in/linh-pham-ptdl/,https://www.linkedin.com/in/tuan-tran-fme849/,https://www.linkedin.com/in/chloe-ngoc-396440185/,https://www.linkedin.com/in/tanlethanh,https://www.linkedin.com/in/devtronghieu,https://www.linkedin.com/in/minh-pham-13a31922a/',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Tools & Infrastructure',
    demoUrl: 'https://www.youtube.com/watch?v=_8NZZKDQ5hM&t=2s',
    category: '',
    superteamMember: 'Vietnam',
  },
  {
    order: 57,
    createdAt: '3/23/2023 1:54:37',
    email_id: 'team@jimsim.io',
    name: 'JimSim',
    description:
      'DeFi Yield Analytics Platform - Analyze historic performance and risk metrics of any yield product that has an APY metric',
    logoUrl:
      'https://drive.google.com/file/d/1hTYmgYKxJkC-kvoE6rczL24XXLZdjrF7/view',
    productUrl: 'https://jimsim.io',
    codeUrl: '(only accessible to judges)',
    projectUrls: '',
    teamLeadName: 'Pierre Martinow',
    teamLeadEmail: 'team@jimsim.io',
    teamLeadSocialUrl: 'https://t.me/DeFi_Koopman',
    teamMembersNames: 'Mo, Vlad, Ali, Barbossa, Paddy',
    teamMembersEmails:
      'sophiesivolap@gmail.com,a.honari@danalytica.com,vladhgost@gmail.com,anvandel@proton.me,paddy@chaindna.io,scderya@gmail.com',
    teamMembersSocialUrls:
      'https://twitter.com/mo_solah,https://twitter.com/CryptoBarbossa,https://twitter.com/syvolape,https://twitter.com/chaindna_io,https://twitter.com/SocioCrypto,https://twitter.com/VladPozniakov',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DeFi, Tools & Infrastructure',
    demoUrl: 'https://demo.jimsim.io',
    category: '',
    superteamMember: 'Turkey',
  },
  {
    order: 58,
    createdAt: '3/23/2023 3:08:17',
    email_id: 'antonio.figueroa@loadtrail.com',
    name: 'Vote.ly',
    description:
      'An innovative blockchain-based platform that leverages decentralized storage to enhance the security, transparency, and accuracy of surveys.',
    logoUrl:
      'https://drive.google.com/file/d/18zjoLgIn59nf2uHHid8auMFFF-PrG5VR/view',
    productUrl: '',
    codeUrl: 'https://github.com/Sitka-ken/votely',
    projectUrls: '',
    teamLeadName: 'Antonio Figueroa Gonzalez',
    teamLeadEmail: 'antoniofigueroa545@gmail.com',
    teamLeadSocialUrl: 'https://es-la.facebook.com/yamiSitka',
    teamMembersNames:
      'Ami Evelyn Saenz Banda,Luis Mario Sandoval Gonzalez,Jose Angel Flores Gutiérrez,Ever Leonardo Chavira Vega,Daniel Omar Caraveo Falcon',
    teamMembersEmails:
      'a_evelyn2023@hotmail.com,19610660@itcdcuauhtemoc.edu.mx,LC19610676@cdcuauhtemoc.tecnm.mx,Leonardo362@live.com,caraveofalcon@gmail.com',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Consumer, Tools & Infrastructure',
    demoUrl: 'https://youtube.com/watch?v=ImSaE8xxLpE&si=EnSIkaIECMiOmarE',
    category: '',
    superteamMember: 'Mexico',
  },
  {
    order: 59,
    createdAt: '3/23/2023 12:23:15',
    email_id: 'chauhandhiraj40@gmail.com',
    name: 'SAGAnize',
    description:
      'A Mobile Suite for dApps that simplifies Solana Mobile development. This way developers can focus on core features while we handle the most common features in Solana Mobile.',
    logoUrl:
      'https://drive.google.com/file/d/1FpoRQMLWaGwosBTaP9MkkU3c8K9nCWov/view',
    productUrl:
      'https://app.pitch.com/app/presentation/d87b1d68-dba6-4cf9-8121-116f69fae996/e966fc8e-b859-4c35-8b25-015f88962db8',
    codeUrl: 'https://github.com/SAGAnize',
    projectUrls: '',
    teamLeadName: 'Dhiraj Chauhan',
    teamLeadEmail: 'chauhandhiraj40@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/cdhiraj40',
    teamMembersNames: 'Anam Ansari,Osheen Mahajan',
    teamMembersEmails: 'anamansari062@gmail.com,mahajan13osheen@gmail.com',
    teamMembersSocialUrls:
      'https://twitter.com/anamansari062,https://twitter.com/Osh_mahajan',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Mobile, Payments, Tools & Infrastructure',
    demoUrl: 'https://www.loom.com/share/020533e8538f4f26b4be11460689449a',
    category: '',
    superteamMember: 'India',
  },
  {
    order: 60,
    createdAt: '3/23/2023 12:33:45',
    email_id: 'bhagyamudgal@gmail.com',
    name: 'NotiSol',
    description:
      'The multi-channel notification service for all your Solana wallet activity! Get real-time alerts via email, SMS, and other platforms.',
    logoUrl:
      'https://drive.google.com/file/d/1VihrUR8rvFCjLXSTtYZmQ_m2DDQSWjF_/view',
    productUrl: 'http://notisol.xyz/',
    codeUrl: 'https://github.com/bhagyamudgal/notisol',
    projectUrls: '',
    teamLeadName: 'Bhagya Mudgal',
    teamLeadEmail: 'bhagyamudgal@gmail.com',
    teamLeadSocialUrl: 'https://twitter.com/BhagyaMudgal',
    teamMembersNames: 'Aarushe',
    teamMembersEmails: 'aarushework@gmail.com',
    teamMembersSocialUrls: 'https://twitter.com/aarushe_reddy',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Consumer, Tools & Infrastructure',
    demoUrl: 'https://loom.com/share/4e83e0eb28ad4802bbf68139eeaa7b67',
    category: '',
    superteamMember: 'India',
  },
  {
    order: 61,
    createdAt: '',
    email_id: 'heyaabis@gmail.com',
    name: 'SOL Trek',
    description: 'A visual and interactive Solana learning platform.',
    logoUrl:
      'https://api.typeform.com/responses/files/901f92e1bda32584e0bf84ac88f51b1aacd088417d858b902c38cea9da0d7ce3/Logo.png',
    productUrl: 'https://pitch.com/public/58fdcb12-5e7b-4c35-b8d4-10b689f1114e',
    codeUrl: 'https://github.com/GitBolt/SOLTrek',
    projectUrls: '',
    teamLeadName: 'Syed Aabis',
    teamLeadEmail: '',
    teamLeadSocialUrl: '',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'Consumer, Tools & Infrastructure',
    demoUrl: '',
    category: 'Web3 Consumer, Infrastructure & Tooling',
    superteamMember: 'India',
  },
  {
    order: 62,
    createdAt: '',
    email_id: 'sahilpal67@gmail.com',
    name: 'Land deeds on blockchain as NFTs',
    description:
      'Solves the problem of land registration frauds using blockchain and patented approach',
    logoUrl:
      'https://api.typeform.com/responses/files/2bf4ea3ab18beaa79e15c1c026b43b5f944ac8a0367e25b002e2905604a3f75c/logo.jpg',
    productUrl:
      'https://drive.google.com/file/d/1uyVef-cO6I6Xn9y1OMiftR-ZHW1QKxeP/view?usp=share_link',
    codeUrl: 'https://github.com/sahil-pal/LandDeedsDapp',
    projectUrls: '',
    teamLeadName: 'sahil',
    teamLeadEmail: '',
    teamLeadSocialUrl: '',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DeFi, Consumer',
    demoUrl: '',
    category: 'DeFi, Web3 Consumer',
    superteamMember: 'India',
  },
  {
    order: 63,
    createdAt: '',
    email_id: 'atlantian001@dropchain.in',
    name: 'Atlantis DAO',
    description:
      'Mobile app built on Solana to earn from verifiable impact data points on chain, used by green and social impact projects.',
    logoUrl:
      'https://api.typeform.com/responses/files/ac4fb4b01e1f7e62e499a18fb6f96155f1150ad65a9e8c373e63f741772663b3/Atlantis_DAO_Logo.png',
    productUrl:
      'https://drive.google.com/drive/folders/1a2_qLJLnEMAHDj6qil1yK7mRk8qX5Prn?usp=share_link',
    codeUrl: 'https://github.com/AtlantisDAO1/atlantis-blockchain',
    projectUrls: '',
    teamLeadName: 'Irthu',
    teamLeadEmail: '',
    teamLeadSocialUrl: '',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DAOs and Network States, Mobile, Consumer',
    demoUrl: '',
    category: 'DAOs, Mobile, Web3 Consumer',
    superteamMember: 'India',
  },
  {
    order: 64,
    createdAt: '',
    email_id: 'adil@vayoo.markets',
    name: 'Vayoo Markets',
    description:
      'Building a scalable solution on providing onchain-liquidity for traditional markets. \n\nEnabling you to trade equity / rates / commodity..etc\n\neg: SPX, NIFTY',
    logoUrl:
      'https://api.typeform.com/responses/files/6002ed5799b3947812d4495d2acf81ecefb6ae7137c0dbd0942531570612fdc2/vayoo_logo.jpg',
    productUrl:
      'https://drive.google.com/file/d/1msZp0xGupDDT1W9is_5NhFwraoJaHS1a/view?usp=sharing',
    codeUrl: 'https://github.com/orgs/Vayoo-Labs/repositories',
    projectUrls: '',
    teamLeadName: 'Muhammed',
    teamLeadEmail: '',
    teamLeadSocialUrl: '',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DeFi, Consumer',
    demoUrl: '',
    category: 'DeFi, Web3 Consumer',
    superteamMember: 'India',
  },
  {
    order: 65,
    createdAt: '',
    email_id: 'raj@truts.xyz',
    name: 'Truts',
    description:
      'Discovery platform for web3 projects with metrics like missions, reviews, social details and others',
    logoUrl:
      'https://api.typeform.com/responses/files/a7f2c25efeede377d8859db250aebd3825bb462fd9c97ecff6affa000791d6b7/Truts_Logo_1.png',
    productUrl: 'https://pitch.com/public/f2c1183a-67ea-4635-b9f2-201077122df4',
    codeUrl: 'https://we.haveSubmitted.onmail',
    projectUrls: '',
    teamLeadName: 'Raj',
    teamLeadEmail: '',
    teamLeadSocialUrl: '',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DAOs and Network States, Consumer, Tools & Infrastructure, Mobile',
    demoUrl: '',
    category: 'DAOs, Web3 Consumer, Infrastructure & Tooling, Mobile',
    superteamMember: 'India',
  },
  {
    order: 66,
    createdAt: '',
    email_id: 'shukarsh@gmail.com',
    name: 'Cordelia',
    description: 'Treasury Management Solution for DAOs and Web3 communities',
    logoUrl:
      'https://api.typeform.com/responses/files/789032a8ad5e1f2fc764fc4eaa79ec8c5af99611365a767eb6fad4e880ec0bb7/icon.png',
    productUrl:
      'https://docs.google.com/presentation/d/1TgxJqSEx4xa9sasdJsJawFZisGM7OB5b_smFjr-pLXo/edit?usp=sharing',
    codeUrl: 'https://github.com/Cordelia-Program/Cordelia-Anchor',
    projectUrls: '',
    teamLeadName: 'Utkarsh',
    teamLeadEmail: '',
    teamLeadSocialUrl: '',
    teamMembersNames: '',
    teamMembersEmails: '',
    teamMembersSocialUrls: '',
    teamLeadDiscordId: '',
    teamMembersDiscordIds: '',
    track: 'DAOs and Network States',
    demoUrl: '',
    category: 'DAOs',
    superteamMember: 'India',
  },
];
